import re

with open('i18n.js', 'r', encoding='utf-8') as f:
    content = f.read()

es_vars = [
    '"charge_title": "Cobrar servicio",', '"charge_client": "Cliente:",', '"charge_service": "Servicio:",',
    '"charge_balance": "Saldo:",', '"charge_amount_label": "Monto a cobrar",', '"charge_confirm": "Confirmar cobro",',
    '"pay_method_title": "Método de pago",', '"pay_method_subtitle": "¿Cómo recibiste el pago?",',
    '"pay_method_cash": "Efectivo (recibí dinero)",', '"pay_method_other": "Otro medio (tarjeta, Yappy, etc.)",',
    '"receipt_title": "Recibo",', '"receipt_print": "Imprimir",', '"receipt_footer": "Recibo generado por Punto Pago",',
    '"menu_title": "Menú",', '"menu_subtitle": "Personaliza tu terminal y equipo",', '"menu_cashout": "Retirar fondos",',
    '"menu_banks": "Bancos y ganancias",', '"menu_setup": "Setup",', '"menu_setup_desc": "Ajustes del comercio",',
    '"menu_team": "Mi equipo",', '"menu_team_desc": "Accesos y roles",', '"menu_team_users": "Usuarios",',
    '"menu_team_users_desc": "Gestiona accesos al portal",', '"config_recurring": "Configurar cobro recurrente",',
    '"config_recurring_desc": "Puedes autorizar cobros mensuales o permitir que PuntoPago cobre cuando el operador facture.",',
    '"recurring_monthly": "Cobro mensual",', '"recurring_monthly_desc": "— elegir día del mes",',
    '"recurring_day": "Día del mes:",', '"recurring_invoice": "Autorizar en factura",',
    '"recurring_invoice_desc": "— PuntoPago podrá cobrar cuando el operador facture",',
    '"recurring_auth_desc": "Autorizo a PuntoPago a cobrar en mi nombre cuando el operador facture.",',
    '"delivery_title": "¿Cómo quieres recibir el comprobante?",', '"delivery_desc": "Elige uno de los canales disponibles y completa la información.",',
    '"confirm_title": "Pago confirmado",', '"confirm_thanks": "Gracias por tu pago de",',
    '"confirm_sent_via": "Se envió el comprobante vía",', '"confirm_share": "Compartir",',
    '"confirm_done": "Listo",', '"confirm_share_hint": "Desde tu teléfono puedes usar el botón \\\"Compartir\\\" para enviar el comprobante por otra app.",'
]

en_vars = [
    '"charge_title": "Charge Service",', '"charge_client": "Client:",', '"charge_service": "Service:",',
    '"charge_balance": "Balance:",', '"charge_amount_label": "Amount to charge",', '"charge_confirm": "Confirm Charge",',
    '"pay_method_title": "Payment Method",', '"pay_method_subtitle": "How did you receive the payment?",',
    '"pay_method_cash": "Cash (received money)",', '"pay_method_other": "Other (card, Yappy, etc.)",',
    '"receipt_title": "Receipt",', '"receipt_print": "Print",', '"receipt_footer": "Receipt generated by Punto Pago",',
    '"menu_title": "Menu",', '"menu_subtitle": "Customize your terminal and team",', '"menu_cashout": "Withdraw funds",',
    '"menu_banks": "Banks and earnings",', '"menu_setup": "Setup",', '"menu_setup_desc": "Business settings",',
    '"menu_team": "My team",', '"menu_team_desc": "Access and roles",', '"menu_team_users": "Users",',
    '"menu_team_users_desc": "Manage access to the portal",', '"config_recurring": "Set up recurrent payment",',
    '"config_recurring_desc": "You can authorize monthly charges or allow PuntoPago to charge when the operator invoices.",',
    '"recurring_monthly": "Monthly charge",', '"recurring_monthly_desc": "— choose day of the month",',
    '"recurring_day": "Day of the month:",', '"recurring_invoice": "Authorize on invoice",',
    '"recurring_invoice_desc": "— PuntoPago can charge when the operator invoices",',
    '"recurring_auth_desc": "I authorize PuntoPago to charge on my behalf when the operator invoices.",',
    '"delivery_title": "How do you want to receive the receipt?",', '"delivery_desc": "Choose one of the available channels and complete the information.",',
    '"confirm_title": "Payment confirmed",', '"confirm_thanks": "Thanks for your payment of",',
    '"confirm_sent_via": "The receipt was sent via",', '"confirm_share": "Share",',
    '"confirm_done": "Done",', '"confirm_share_hint": "From your phone you can use the \\\"Share\\\" button to send the receipt via another app.",'
]

zh_vars = [
    '"charge_title": "收费服务",', '"charge_client": "客户：",', '"charge_service": "服务：",',
    '"charge_balance": "余额：",', '"charge_amount_label": "收费金额",', '"charge_confirm": "确认收费",',
    '"pay_method_title": "付款方式",', '"pay_method_subtitle": "您是如何收到付款的？",',
    '"pay_method_cash": "现金（已收钱）",', '"pay_method_other": "其他（卡，Yappy等）",',
    '"receipt_title": "收据",', '"receipt_print": "打印",', '"receipt_footer": "收据由 Punto Pago 生成",',
    '"menu_title": "菜单",', '"menu_subtitle": "自定义终端和团队",', '"menu_cashout": "提取资金",',
    '"menu_banks": "银行和收益",', '"menu_setup": "设置",', '"menu_setup_desc": "业务设置",',
    '"menu_team": "我的团队",', '"menu_team_desc": "访问和角色",', '"menu_team_users": "用户",',
    '"menu_team_users_desc": "管理对门户的访问",', '"config_recurring": "设置定期付款",',
    '"config_recurring_desc": "您可以授权每月收费，或允许 PuntoPago 在运营商开票时收费。",',
    '"recurring_monthly": "每月收费",', '"recurring_monthly_desc": "— 选择每月的哪一天",',
    '"recurring_day": "每月的某天：",', '"recurring_invoice": "在发票上授权",',
    '"recurring_invoice_desc": "— 运营商开票时 PuntoPago 可以收费",',
    '"recurring_auth_desc": "我授权 PuntoPago 在运营商开票时代表我收费。",',
    '"delivery_title": "您希望如何接收收据？",', '"delivery_desc": "选择可用的渠道之一并填写信息。",',
    '"confirm_title": "付款已确认",', '"confirm_thanks": "感谢您支付",',
    '"confirm_sent_via": "收据已通过发送",', '"confirm_share": "分享",',
    '"confirm_done": "完成",', '"confirm_share_hint": "您可以使用手机上的“分享”按钮通过其他应用程序发送收据。",'
]

ru_vars = [
    '"charge_title": "Платная услуга",', '"charge_client": "Клиент:",', '"charge_service": "Услуга:",',
    '"charge_balance": "Баланс:",', '"charge_amount_label": "Сумма к оплате",', '"charge_confirm": "Подтвердить оплату",',
    '"pay_method_title": "Способ оплаты",', '"pay_method_subtitle": "Как вы получили оплату?",',
    '"pay_method_cash": "Наличные",', '"pay_method_other": "Другое (карта, Yappy и т.д.)",',
    '"receipt_title": "Квитанция",', '"receipt_print": "Печать",', '"receipt_footer": "Квитанция сгенерирована Punto Pago",',
    '"menu_title": "Меню",', '"menu_subtitle": "Настройка терминала и команды",', '"menu_cashout": "Вывод средств",',
    '"menu_banks": "Банки и доходы",', '"menu_setup": "Настройки",', '"menu_setup_desc": "Настройки бизнеса",',
    '"menu_team": "Моя команда",', '"menu_team_desc": "Доступ и роли",', '"menu_team_users": "Пользователи",',
    '"menu_team_users_desc": "Управление доступом к порталу",', '"config_recurring": "Настроить регулярный платеж",',
    '"config_recurring_desc": "Вы можете разрешить ежемесячные списания или позволить PuntoPago списывать при выставлении счета оператором.",',
    '"recurring_monthly": "Ежемесячный платеж",', '"recurring_monthly_desc": "— выбрать день месяца",',
    '"recurring_day": "День месяца:",', '"recurring_invoice": "Авторизовать по счету",',
    '"recurring_invoice_desc": "— PuntoPago может списывать при выставлении счета оператором",',
    '"recurring_auth_desc": "Я уполномочиваю PuntoPago списывать средства от моего имени при выставлении счета оператором.",',
    '"delivery_title": "Как вы хотите получить квитанцию?",', '"delivery_desc": "Выберите один из доступных каналов и заполните информацию.",',
    '"confirm_title": "Платеж подтвержден",', '"confirm_thanks": "Спасибо за ваш платеж в размере",',
    '"confirm_sent_via": "Квитанция была отправлена через",', '"confirm_share": "Поделиться",',
    '"confirm_done": "Готово",', '"confirm_share_hint": "С вашего телефона вы можете использовать кнопку «Поделиться», чтобы отправить квитанцию через другое приложение.",'
]

def insert_lang(code, block):
    global content
    lang_match = re.search(r'' + code + ':\s*\{([^}]*)\}', content)
    if lang_match:
        inner = lang_match.group(1)
        newlines = "\\n      " + "\\n      ".join(block) + "\\n      "
        new_inner = newlines + inner.strip()
        replaced = "  " + code + ": {\n      " + new_inner + "\n    }"
        content = content[:lang_match.start()] + replaced + content[lang_match.end():]

insert_lang('es', es_vars)
insert_lang('en', en_vars)
insert_lang('zh', zh_vars)
insert_lang('ru', ru_vars)

with open('i18n.js', 'w', encoding='utf-8') as f:
    f.write(content)
